@startuml Optimizer
skinparam linetype ortho
interface Parameter <<interface>> {
    +plus(Parameter)
    +minus(Parameter) 
}

class Euclidean
class Spherical

interface Optimizer <<interface>> {
    + minimize(in: x)
    + step(in: x)
    + addCost(in: cost)
    - List<Cost> costs
}

interface Cost <<interface>> {
    + computeCost(in: x): sum
    + computeJacobian(in: x, out: jacobian): sum
    + linearize(in:x, out: hessian, out: b)
}

class NumericalDiffCost {

}

class AnalyticalDiffCost {
    
}

class LevenbergMarquadt {

}

Parameter <|.. Euclidean
Parameter <|.. Spherical


Parameter <.. Optimizer
Parameter <.. Cost
Optimizer "1" o- "   1..*  " Cost

Cost <|.. AnalyticalDiffCost
Cost <|.. NumericalDiffCost

Optimizer <|.. LevenbergMarquadt
@enduml